export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_FAILURE_STATUS: 'LOGIN_FAILURE_STATUS',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const adminContants = {
    USER_CREATE_REQUEST: 'USER_CREATE_REQUEST',
    USER_CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
    USER_CREATE_FAILURE: 'USER_CREATE_FAILURE',
}


export const roleContants = {
    GET_ALL_ROLE_REQUEST: 'GET_ALL_ROLE_REQUEST',
    GET_ALL_ROLE_SUCCESS: 'GET_ALL_ROLE_SUCCESS',
    GET_ALL_ROLE_FAILURE: 'GET_ALL_ROLE_FAILURE',

    ADD_NEW_ROLE_REQUEST: 'ADD_NEW_ROLE_REQUEST',
    ADD_NEW_ROLE_SUCCESS: 'ADD_NEW_ROLE_SUCCESS',
    ADD_NEW_ROLE_FAILURE: 'ADD_NEW_ROLE_FAILURE',
    NEW_ROLE_RESET: "NEW_ROLE_RESET",

    UPDATE_ROLE_REQUEST: "UPDATE_ROLE_REQUEST",
    UPDATE_ROLE_SUCCESS: "UPDATE_ROLE_SUCCESS",
    UPDATE_ROLE_FAILURE: "UPDATE_ROLE_FAILURE",
    UPDATE_ROLE_RESET: "UPDATE_ROLE_RESET",

    DELETE_ROLE_REQUEST: "DELETE_ROLE_REQUEST",
    DELETE_ROLE_SUCCESS: "DELETE_ROLE_SUCCESS",
    DELETE_ROLE_FAILURE: "DELETE_ROLE_FAILURE",
    DELETE_ROLE_RESET: "DELETE_ROLE_RESET",

    GET_SINGLE_ROLE_REQUEST: 'GET_SINGLE_ROLE_REQUEST',
    GET_SINGLE_ROLE_SUCCESS: 'GET_SINGLE_ROLE_SUCCESS',
    GET_SINGLE_ROLE_FAILURE: 'GET_SINGLE_ROLE_FAILURE',

}

export const CLEAR_ERRORS = "CLEAR_ERRORS";


// FOR CUSTOMER CONTANTS
export const userContant = {
    ALL_USERS_REQUEST: "ALL_USERS_REQUEST",
    ALL_USERS_SUCCESS: "ALL_USERS_SUCCESS",
    ALL_USERS_FAIL: "ALL_USERS_FAIL",
    CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
    CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
    CREATE_USER_FAIL: "CREATE_USER_FAIL",
    GET_SINGLE_USER_REQUEST: 'GET_SINGLE_USER_REQUEST',
    GET_SINGLE_USER_SUCCESS: 'GET_SINGLE_USER_SUCCESS',
    GET_SINGLE_USER_FAILURE: 'GET_SINGLE_USER_FAILURE',
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    UPDATE_USER_RESET: 'UPDATE_USER_RESET',
    DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'DELETE_USER_FAILURE',
    DELETE_USER_RESET: 'DELETE_USER_RESET',

    GET_CALL_HISTORY_REQUEST: 'GET_CALL_HISTORY_REQUEST',
    GET_CALL_HISTORY_SUCCESS: 'GET_CALL_HISTORY_SUCCESS',
    GET_CALL_HISTORY_FAIL: 'GET_CALL_HISTORY_FAIL'

}



// FOR ASTROLOGER CONTANTS
export const astroloerContant = {
    ALL_ASTROLOGER_REQUEST: "ALL_ASTROLOGER_REQUEST",
    ALL_ASTROLOGER_SUCCESS: "ALL_ASTROLOGER_SUCCESS",
    ALL_ASTROLOGER_FAIL: "ALL_ASTROLOGER_FAIL",
    CREATE_ASTROLOGER_REQUEST: "CREATE_ASTROLOGER_REQUEST",
    CREATE_ASTROLOGER_SUCCESS: "CREATE_ASTROLOGER_SUCCESS",
    CREATE_ASTROLOGER_FAIL: "CREATE_ASTROLOGER_FAIL",
    GET_SINGLE_ASTROLOGER_REQUEST: 'GET_SINGLE_ASTROLOGER_REQUEST',
    GET_SINGLE_ASTROLOGER_SUCCESS: 'GET_SINGLE_ASTROLOGER_SUCCESS',
    GET_SINGLE_ASTROLOGER_FAILURE: 'GET_SINGLE_ASTROLOGER_FAILURE',
    UPDATE_ASTROLOGER_REQUEST: 'UPDATE_ASTROLOGER_REQUEST',
    UPDATE_ASTROLOGER_SUCCESS: 'UPDATE_ASTROLOGER_SUCCESS',
    UPDATE_ASTROLOGER_FAILURE: 'UPDATE_ASTROLOGER_FAILURE',
    UPDATE_ASTROLOGER_RESET: 'UPDATE_ASTROLOGER_RESET',
    DELETE_ASTROLOGER_REQUEST: 'DELETE_ASTROLOGER_REQUEST',
    DELETE_ASTROLOGER_SUCCESS: 'DELETE_ASTROLOGER_SUCCESS',
    DELETE_ASTROLOGER_FAILURE: 'DELETE_ASTROLOGER_FAILURE',
    DELETE_ASTROLOGER_RESET: 'DELETE_ASTROLOGER_RESET',

}


// SERVICE CONTANT START

export const serviceContant = {
    ALL_SERVICE_REQUEST: 'ALL_SERVICE_REQUEST',
    ALL_SERVICE_SUCCESS: 'ALL_SERVICE_SUCCESS',
    ALL_SERVICE_FAIL: 'ALL_SERVICE_FAIL',

    CREATE_SERVICE_REQUEST: 'CREATE_SERVICE_REQUEST',
    CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
    CREATE_SERVICE_FAIL: 'CREATE_SERVICE_FAIL',

    DELETE_SERVICE_REQUEST: 'DELETE_SERVICE_REQUEST',
    DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
    DELETE_SERVICE_FAILURE: 'DELETE_SERVICE_FAILURE',

    GET_SINGLE_SERVICE_REQUEST:'GET_SINGLE_SERVICE_REQUEST',
    GET_SINGLE_SERVICE_SUCCESS:'GET_SINGLE_SERVICE_SUCCESS',
    GET_SINGLE_SERVICE_FAILURE:'GET_SINGLE_SERVICE_FAILURE',

    UPDATE_SERVICE_REQUEST:'UPDATE_SERVICE_REQUEST',
    UPDATE_SERVICE_SUCCESS:'UPDATE_SERVICE_SUCCESS',
    UPDATE_SERVICE_FAILURE:'UPDATE_SERVICE_FAILURE',

}

// BANNER CONTANT START
export const bannerContant = {
    ALL_BANNER_REQUEST: 'ALL_BANNER_REQUEST',
    ALL_BANNER_SUCCESS: 'ALL_BANNER_SUCCESS',
    ALL_BANNER_FAIL: 'ALL_BANNER_FAIL',

    CREATE_BANNER_REQUEST: 'CREATE_BANNER_REQUEST',
    CREATE_BANNER_SUCCESS: 'CREATE_BANNER_SUCCESS',
    CREATE_BANNER_FAIL: 'CREATE_BANNER_FAIL',

    DELETE_BANNER_REQUEST: 'DELETE_BANNER_REQUEST',
    DELETE_BANNER_SUCCESS: 'DELETE_BANNER_SUCCESS',
    DELETE_BANNER_FAILURE: 'DELETE_BANNER_FAILURE',

}


// BLOG CATEGORY CONTANT START

export const blogCategoryContant = {
    ALL_BLOGCATEGORY_REQUEST: 'ALL_BLOGCATEGORY_REQUEST',
    ALL_BLOGCATEGORY_SUCCESS: 'ALL_BLOGCATEGORY_SUCCESS',
    ALL_BLOGCATEGORY_FAIL: 'ALL_BLOGCATEGORY_FAIL',

    CREATE_BLOGCATEGORY_REQUEST: 'CREATE_BLOGCATEGORY_REQUEST',
    CREATE_BLOGCATEGORY_SUCCESS: 'CREATE_BLOGCATEGORY_SUCCESS',
    CREATE_BLOGCATEGORY_FAIL: 'CREATE_BLOGCATEGORY_FAIL',

    DELETE_BLOGCATEGORY_REQUEST: 'DELETE_BLOGCATEGORY_REQUEST',
    DELETE_BLOGCATEGORY_SUCCESS: 'DELETE_BLOGCATEGORY_SUCCESS',
    DELETE_BLOGCATEGORY_FAILURE: 'DELETE_BLOGCATEGORY_FAILURE',

    GET_SINGLE_BLOGCATEGORY_REQUEST:'GET_SINGLE_BLOGCATEGORY_REQUEST',
    GET_SINGLE_BLOGCATEGORY_SUCCESS:'GET_SINGLE_BLOGCATEGORY_SUCCESS',
    GET_SINGLE_BLOGCATEGORY_FAILURE:'GET_SINGLE_BLOGCATEGORY_FAILURE',

    UPDATE_BLOGCATEGORY_REQUEST:'UPDATE_BLOGCATEGORY_REQUEST',
    UPDATE_BLOGCATEGORY_SUCCESS:'UPDATE_BLOGCATEGORY_SUCCESS',
    UPDATE_BLOGCATEGORY_FAILURE:'UPDATE_BLOGCATEGORY_FAILURE',

}


// BLOG PRINT 
export const blogContant = {
    ALL_BLOG_REQUEST: 'ALL_BLOG_REQUEST',
    ALL_BLOG_SUCCESS: 'ALL_BLOG_SUCCESS',
    ALL_BLOG_FAIL: 'ALL_BLOG_FAIL',

    CREATE_BLOG_REQUEST: 'CREATE_BLOG_REQUEST',
    CREATE_BLOG_SUCCESS: 'CREATE_BLOG_SUCCESS',
    CREATE_BLOG_FAIL: 'CREATE_BLOG_FAIL',

    DELETE_BLOG_REQUEST: 'DELETE_BLOG_REQUEST',
    DELETE_BLOG_SUCCESS: 'DELETE_BLOG_SUCCESS',
    DELETE_BLOG_FAILURE: 'DELETE_BLOG_FAILURE',

    GET_SINGLE_BLOG_REQUEST:'GET_SINGLE_BLOG_REQUEST',
    GET_SINGLE_BLOG_SUCCESS:'GET_SINGLE_BLOG_SUCCESS',
    GET_SINGLE_BLOG_FAILURE:'GET_SINGLE_BLOG_FAILURE',

    UPDATE_BLOG_REQUEST:'UPDATE_BLOG_REQUEST',
    UPDATE_BLOG_SUCCESS:'UPDATE_BLOG_SUCCESS',
    UPDATE_BLOG_FAILURE:'UPDATE_BLOG_FAILURE',

}


// PRODUCT CATEGORY ROUTE
export const categoryContant = {
    ALL_CATEGORY_REQUEST: 'ALL_CATEGORY_REQUEST',
    ALL_CATEGORY_SUCCESS: 'ALL_CATEGORY_SUCCESS',
    ALL_CATEGORY_FAIL: 'ALL_CATEGORY_FAIL',

    CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAIL: 'CREATE_CATEGORY_FAIL',

    DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILURE: 'DELETE_CATEGORY_FAILURE',

    GET_SINGLE_CATEGORY_REQUEST:'GET_SINGLE_CATEGORY_REQUEST',
    GET_SINGLE_CATEGORY_SUCCESS:'GET_SINGLE_CATEGORY_SUCCESS',
    GET_SINGLE_CATEGORY_FAILURE:'GET_SINGLE_CATEGORY_FAILURE',

    UPDATE_CATEGORY_REQUEST:'UPDATE_CATEGORY_REQUEST',
    UPDATE_CATEGORY_SUCCESS:'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAILURE:'UPDATE_CATEGORY_FAILURE',

}


// DASHBORD USER START CHART
export const dashboardContant = {
    ALL_USERCHART_REQUEST: 'ALL_USERCHART_REQUEST',
    ALL_USERCHART_SUCCESS: 'ALL_USERCHART_SUCCESS',
    ALL_USERCHART_FAIL: 'ALL_USERCHART_FAIL',
}


// PRODUCT CONSTANTS
export const productContant = {
    ALL_PRODUCT_REQUEST: 'ALL_PRODUCT_REQUEST',
    ALL_PRODUCT_SUCCESS: 'ALL_PRODUCT_SUCCESS',
    ALL_PRODUCT_FAIL: 'ALL_PRODUCT_FAIL',

    CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_SUCCESS: 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAIL: 'CREATE_PRODUCT_FAIL',

    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',

    GET_SINGLE_PRODUCT_REQUEST:'GET_SINGLE_PRODUCT_REQUEST',
    GET_SINGLE_PRODUCT_SUCCESS:'GET_SINGLE_PRODUCT_SUCCESS',
    GET_SINGLE_PRODUCT_FAILURE:'GET_SINGLE_PRODUCT_FAILURE',

    UPDATE_PRODUCT_REQUEST:'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_SUCCESS:'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE:'UPDATE_PRODUCT_FAILURE',

}